/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerCard = IDL.Record({
  'id' : IDL.Text,
  'cvv' : IDL.Text,
  'balance' : IDL.Float64,
  'cardName' : IDL.Text,
  'customerUsername' : IDL.Text,
  'expirationDate' : IDL.Text,
  'cardColor' : IDL.Text,
  'customerId' : IDL.Text,
  'cardNumber' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'category' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
});
export const Time = IDL.Int;
export const CustomerOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'total' : IDL.Float64,
  'paymentMethod' : IDL.Opt(IDL.Text),
  'wPayCode' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'items' : IDL.Vec(MenuItem),
});
export const GiftCard = IDL.Record({
  'balance' : IDL.Float64,
  'code' : IDL.Text,
});

export const idlService = IDL.Service({
  'activateCardDevice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addCardBalance' : IDL.Func(
      [IDL.Text, IDL.Float64],
      [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
      [],
    ),
  'addCustomCreditCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)], [], []),
  'addRewardPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'clearPairingCode' : IDL.Func([IDL.Text], [], []),
  'completeTransaction' : IDL.Func(
      [IDL.Vec(MenuItem), IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'createWPayOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
      [IDL.Text],
      [],
    ),
  'deleteCustomerCard' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'editMenuItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'generateCustomerCard' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
      [],
    ),
  'generatePairingCode' : IDL.Func([], [IDL.Text], []),
  'generatePaymentCode' : IDL.Func(
      [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
      [IDL.Text],
      [],
    ),
  'getAllCustomerCards' : IDL.Func([], [IDL.Vec(CustomerCard)], ['query']),
  'getCustomerCards' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(CustomerCard), 'err' : IDL.Text })],
      [],
    ),
  'getCustomerOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getCustomerProfile' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'cards' : IDL.Vec(CustomerCard),
            'orders' : IDL.Vec(CustomerOrder),
            'points' : IDL.Nat,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'getDailySalesSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'topItems' : IDL.Vec(
            IDL.Record({ 'name' : IDL.Text, 'quantity' : IDL.Nat })
          ),
          'orderCount' : IDL.Nat,
          'totalRevenue' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getGiftCard' : IDL.Func([IDL.Text], [GiftCard], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderByPaymentCode' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CustomerOrder)],
      ['query'],
    ),
  'getPairingCart' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'status' : IDL.Text,
            'total' : IDL.Float64,
            'orderId' : IDL.Opt(IDL.Nat),
            'items' : IDL.Vec(MenuItem),
          })
        ),
      ],
      ['query'],
    ),
  'getPairingStatus' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'active' : IDL.Bool, 'notFound' : IDL.Null })],
      ['query'],
    ),
  'getRewardPoints' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'issueGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'lookupWPayOrder' : IDL.Func([IDL.Text], [IDL.Opt(CustomerOrder)], ['query']),
  'markOrderPaidByCode' : IDL.Func([IDL.Text], [], []),
  'markPairingCodeUsed' : IDL.Func([IDL.Text], [], []),
  'markPairingPaid' : IDL.Func([IDL.Text], [], []),
  'markWPayOrderPaid' : IDL.Func([IDL.Text], [], []),
  'payWithCustomerCard' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
      [],
    ),
  'placeCustomerOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'processCardDevicePayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'redeemForGiftCard' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'redeemRewardPoints' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
  'setPairingOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'signIn' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'signUp' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'updatePairingCart' : IDL.Func(
      [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
      [],
      [],
    ),
  'useGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'validateCustomCreditCard' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'validatePairingCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerCard = IDL.Record({
    'id' : IDL.Text,
    'cvv' : IDL.Text,
    'balance' : IDL.Float64,
    'cardName' : IDL.Text,
    'customerUsername' : IDL.Text,
    'expirationDate' : IDL.Text,
    'cardColor' : IDL.Text,
    'customerId' : IDL.Text,
    'cardNumber' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'category' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
  });
  const Time = IDL.Int;
  const CustomerOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'total' : IDL.Float64,
    'paymentMethod' : IDL.Opt(IDL.Text),
    'wPayCode' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'items' : IDL.Vec(MenuItem),
  });
  const GiftCard = IDL.Record({ 'balance' : IDL.Float64, 'code' : IDL.Text });
  
  return IDL.Service({
    'activateCardDevice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addCardBalance' : IDL.Func(
        [IDL.Text, IDL.Float64],
        [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
        [],
      ),
    'addCustomCreditCard' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'addRewardPoints' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'clearPairingCode' : IDL.Func([IDL.Text], [], []),
    'completeTransaction' : IDL.Func(
        [IDL.Vec(MenuItem), IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'createWPayOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
        [IDL.Text],
        [],
      ),
    'deleteCustomerCard' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'editMenuItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'generateCustomerCard' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
        [],
      ),
    'generatePairingCode' : IDL.Func([], [IDL.Text], []),
    'generatePaymentCode' : IDL.Func(
        [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
        [IDL.Text],
        [],
      ),
    'getAllCustomerCards' : IDL.Func([], [IDL.Vec(CustomerCard)], ['query']),
    'getCustomerCards' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(CustomerCard), 'err' : IDL.Text })],
        [],
      ),
    'getCustomerOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getCustomerProfile' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'cards' : IDL.Vec(CustomerCard),
              'orders' : IDL.Vec(CustomerOrder),
              'points' : IDL.Nat,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'getDailySalesSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'topItems' : IDL.Vec(
              IDL.Record({ 'name' : IDL.Text, 'quantity' : IDL.Nat })
            ),
            'orderCount' : IDL.Nat,
            'totalRevenue' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getGiftCard' : IDL.Func([IDL.Text], [GiftCard], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderByPaymentCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerOrder)],
        ['query'],
      ),
    'getPairingCart' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'status' : IDL.Text,
              'total' : IDL.Float64,
              'orderId' : IDL.Opt(IDL.Nat),
              'items' : IDL.Vec(MenuItem),
            })
          ),
        ],
        ['query'],
      ),
    'getPairingStatus' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'active' : IDL.Bool, 'notFound' : IDL.Null })],
        ['query'],
      ),
    'getRewardPoints' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'issueGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'lookupWPayOrder' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerOrder)],
        ['query'],
      ),
    'markOrderPaidByCode' : IDL.Func([IDL.Text], [], []),
    'markPairingCodeUsed' : IDL.Func([IDL.Text], [], []),
    'markPairingPaid' : IDL.Func([IDL.Text], [], []),
    'markWPayOrderPaid' : IDL.Func([IDL.Text], [], []),
    'payWithCustomerCard' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : CustomerCard, 'err' : IDL.Text })],
        [],
      ),
    'placeCustomerOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'processCardDevicePayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'redeemForGiftCard' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'redeemRewardPoints' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeMenuItem' : IDL.Func([IDL.Nat], [], []),
    'setPairingOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'signIn' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'signUp' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'updatePairingCart' : IDL.Func(
        [IDL.Text, IDL.Vec(MenuItem), IDL.Float64],
        [],
        [],
      ),
    'useGiftCard' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'validateCustomCreditCard' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'validatePairingCode' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };