/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerCard {
  'id' : string,
  'cvv' : string,
  'balance' : number,
  'cardName' : string,
  'customerUsername' : string,
  'expirationDate' : string,
  'cardColor' : string,
  'customerId' : string,
  'cardNumber' : string,
}
export interface CustomerOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'total' : number,
  'paymentMethod' : [] | [string],
  'wPayCode' : [] | [string],
  'timestamp' : Time,
  'items' : Array<MenuItem>,
}
export interface GiftCard { 'balance' : number, 'code' : string }
export interface MenuItem {
  'name' : string,
  'category' : [] | [string],
  'price' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'activateCardDevice' : ActorMethod<[string, bigint], undefined>,
  'addCardBalance' : ActorMethod<
    [string, number],
    { 'ok' : CustomerCard } |
      { 'err' : string }
  >,
  'addCustomCreditCard' : ActorMethod<[string, string], undefined>,
  'addMenuItem' : ActorMethod<[string, number, [] | [string]], undefined>,
  'addRewardPoints' : ActorMethod<[string, bigint], undefined>,
  'clearPairingCode' : ActorMethod<[string], undefined>,
  'completeTransaction' : ActorMethod<
    [Array<MenuItem>, number, string],
    undefined
  >,
  'createWPayOrder' : ActorMethod<[string, Array<MenuItem>, number], string>,
  'deleteCustomerCard' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'editMenuItem' : ActorMethod<
    [bigint, string, number, [] | [string]],
    undefined
  >,
  'generateCustomerCard' : ActorMethod<
    [string, string, string, string],
    { 'ok' : CustomerCard } |
      { 'err' : string }
  >,
  'generatePairingCode' : ActorMethod<[], string>,
  'generatePaymentCode' : ActorMethod<
    [string, Array<MenuItem>, number],
    string
  >,
  'getAllCustomerCards' : ActorMethod<[], Array<CustomerCard>>,
  'getCustomerCards' : ActorMethod<
    [string, string],
    { 'ok' : Array<CustomerCard> } |
      { 'err' : string }
  >,
  'getCustomerOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getCustomerProfile' : ActorMethod<
    [string],
    {
        'ok' : {
          'cards' : Array<CustomerCard>,
          'orders' : Array<CustomerOrder>,
          'points' : bigint,
        }
      } |
      { 'err' : string }
  >,
  'getDailySalesSummary' : ActorMethod<
    [],
    {
      'topItems' : Array<{ 'name' : string, 'quantity' : bigint }>,
      'orderCount' : bigint,
      'totalRevenue' : number,
    }
  >,
  'getGiftCard' : ActorMethod<[string], GiftCard>,
  'getMenu' : ActorMethod<[], Array<MenuItem>>,
  'getMenuByCategory' : ActorMethod<[], Array<MenuItem>>,
  'getOrderByPaymentCode' : ActorMethod<[string], [] | [CustomerOrder]>,
  'getPairingCart' : ActorMethod<
    [string],
    [] | [
      {
        'status' : string,
        'total' : number,
        'orderId' : [] | [bigint],
        'items' : Array<MenuItem>,
      }
    ]
  >,
  'getPairingStatus' : ActorMethod<
    [string],
    { 'active' : boolean } |
      { 'notFound' : null }
  >,
  'getRewardPoints' : ActorMethod<[string], bigint>,
  'issueGiftCard' : ActorMethod<[string, number], undefined>,
  'lookupWPayOrder' : ActorMethod<[string], [] | [CustomerOrder]>,
  'markOrderPaidByCode' : ActorMethod<[string], undefined>,
  'markPairingCodeUsed' : ActorMethod<[string], undefined>,
  'markPairingPaid' : ActorMethod<[string], undefined>,
  'markWPayOrderPaid' : ActorMethod<[string], undefined>,
  'payWithCustomerCard' : ActorMethod<
    [string, number, string, string],
    { 'ok' : CustomerCard } |
      { 'err' : string }
  >,
  'placeCustomerOrder' : ActorMethod<[string, Array<MenuItem>, number], bigint>,
  'processCardDevicePayment' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'redeemForGiftCard' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'redeemRewardPoints' : ActorMethod<[bigint], boolean>,
  'removeMenuItem' : ActorMethod<[bigint], undefined>,
  'setPairingOrder' : ActorMethod<[string, bigint], undefined>,
  'signIn' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'signUp' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'updateOrderStatus' : ActorMethod<[bigint, string, [] | [string]], undefined>,
  'updatePairingCart' : ActorMethod<
    [string, Array<MenuItem>, number],
    undefined
  >,
  'useGiftCard' : ActorMethod<[string, number], undefined>,
  'validateCustomCreditCard' : ActorMethod<[string], string>,
  'validatePairingCode' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];