/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomerOrder {
    id: bigint;
    customerName: string;
    status: string;
    total: number;
    paymentMethod?: string;
    wPayCode?: string;
    timestamp: Time;
    items: Array<MenuItem>;
}
export interface MenuItem {
    name: string;
    category?: string;
    price: number;
}
export interface CustomerCard {
    id: string;
    cvv: string;
    balance: number;
    cardName: string;
    customerUsername: string;
    expirationDate: string;
    cardColor: string;
    customerId: string;
    cardNumber: string;
}
export type Time = bigint;
export interface GiftCard {
    balance: number;
    code: string;
}
export interface backendInterface {
    activateCardDevice(code: string, orderId: bigint): Promise<void>;
    addCardBalance(cardId: string, amount: number): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }>;
    addCustomCreditCard(identifier: string, qrPayload: string): Promise<void>;
    addMenuItem(name: string, price: number, category: string | null): Promise<void>;
    addRewardPoints(username: string, amount: bigint): Promise<void>;
    clearPairingCode(code: string): Promise<void>;
    completeTransaction(items: Array<MenuItem>, total: number, paymentMethod: string): Promise<void>;
    createWPayOrder(customerName: string, items: Array<MenuItem>, total: number): Promise<string>;
    deleteCustomerCard(cardId: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    editMenuItem(index: bigint, name: string, price: number, category: string | null): Promise<void>;
    generateCustomerCard(username: string, password: string, cardName: string, cardColor: string): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }>;
    generatePairingCode(): Promise<string>;
    generatePaymentCode(customerName: string, items: Array<MenuItem>, total: number): Promise<string>;
    getAllCustomerCards(): Promise<Array<CustomerCard>>;
    getCustomerCards(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: Array<CustomerCard>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getCustomerOrders(): Promise<Array<CustomerOrder>>;
    getCustomerProfile(username: string): Promise<{
        __kind__: "ok";
        ok: {
            cards: Array<CustomerCard>;
            orders: Array<CustomerOrder>;
            points: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDailySalesSummary(): Promise<{
        topItems: Array<{
            name: string;
            quantity: bigint;
        }>;
        orderCount: bigint;
        totalRevenue: number;
    }>;
    getGiftCard(code: string): Promise<GiftCard>;
    getMenu(): Promise<Array<MenuItem>>;
    getMenuByCategory(): Promise<Array<MenuItem>>;
    getOrderByPaymentCode(code: string): Promise<CustomerOrder | null>;
    getPairingCart(code: string): Promise<{
        status: string;
        total: number;
        orderId?: bigint;
        items: Array<MenuItem>;
    } | null>;
    getPairingStatus(code: string): Promise<{
        __kind__: "active";
        active: boolean;
    } | {
        __kind__: "notFound";
        notFound: null;
    }>;
    getRewardPoints(username: string): Promise<bigint>;
    issueGiftCard(code: string, balance: number): Promise<void>;
    lookupWPayOrder(code: string): Promise<CustomerOrder | null>;
    markOrderPaidByCode(code: string): Promise<void>;
    markPairingCodeUsed(code: string): Promise<void>;
    markPairingPaid(code: string): Promise<void>;
    markWPayOrderPaid(code: string): Promise<void>;
    payWithCustomerCard(cardId: string, amount: number, username: string, password: string): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }>;
    placeCustomerOrder(customerName: string, items: Array<MenuItem>, total: number): Promise<bigint>;
    processCardDevicePayment(code: string, cardNumber: string, cardName: string, expiryDate: string, cvv: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    redeemForGiftCard(username: string, cardName: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    redeemRewardPoints(points: bigint): Promise<boolean>;
    removeMenuItem(index: bigint): Promise<void>;
    setPairingOrder(code: string, orderId: bigint): Promise<void>;
    signIn(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    signUp(username: string, password: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateOrderStatus(id: bigint, status: string, paymentMethod: string | null): Promise<void>;
    updatePairingCart(code: string, items: Array<MenuItem>, total: number): Promise<void>;
    useGiftCard(code: string, amount: number): Promise<void>;
    validateCustomCreditCard(qrPayload: string): Promise<string>;
    validatePairingCode(code: string): Promise<boolean>;
}
import type { CustomerCard as _CustomerCard, CustomerOrder as _CustomerOrder, MenuItem as _MenuItem, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activateCardDevice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateCardDevice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateCardDevice(arg0, arg1);
            return result;
        }
    }
    async addCardBalance(arg0: string, arg1: number): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addCardBalance(arg0, arg1);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCardBalance(arg0, arg1);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCustomCreditCard(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomCreditCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomCreditCard(arg0, arg1);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: number, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addRewardPoints(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addRewardPoints(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRewardPoints(arg0, arg1);
            return result;
        }
    }
    async clearPairingCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearPairingCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearPairingCode(arg0);
            return result;
        }
    }
    async completeTransaction(arg0: Array<MenuItem>, arg1: number, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeTransaction(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeTransaction(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async createWPayOrder(arg0: string, arg1: Array<MenuItem>, arg2: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWPayOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWPayOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async deleteCustomerCard(arg0: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomerCard(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomerCard(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async editMenuItem(arg0: bigint, arg1: string, arg2: number, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editMenuItem(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editMenuItem(arg0, arg1, arg2, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async generateCustomerCard(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generateCustomerCard(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateCustomerCard(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async generatePairingCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePairingCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePairingCode();
            return result;
        }
    }
    async generatePaymentCode(arg0: string, arg1: Array<MenuItem>, arg2: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePaymentCode(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePaymentCode(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getAllCustomerCards(): Promise<Array<CustomerCard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomerCards();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomerCards();
            return result;
        }
    }
    async getCustomerCards(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: Array<CustomerCard>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerCards(arg0, arg1);
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerCards(arg0, arg1);
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerOrders(): Promise<Array<CustomerOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerProfile(arg0: string): Promise<{
        __kind__: "ok";
        ok: {
            cards: Array<CustomerCard>;
            orders: Array<CustomerOrder>;
            points: bigint;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerProfile(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerProfile(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailySalesSummary(): Promise<{
        topItems: Array<{
            name: string;
            quantity: bigint;
        }>;
        orderCount: bigint;
        totalRevenue: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailySalesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailySalesSummary();
            return result;
        }
    }
    async getGiftCard(arg0: string): Promise<GiftCard> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftCard(arg0);
            return result;
        }
    }
    async getMenu(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenu();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenu();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuByCategory(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuByCategory();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuByCategory();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderByPaymentCode(arg0: string): Promise<CustomerOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderByPaymentCode(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderByPaymentCode(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairingCart(arg0: string): Promise<{
        status: string;
        total: number;
        orderId?: bigint;
        items: Array<MenuItem>;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairingCart(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairingCart(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPairingStatus(arg0: string): Promise<{
        __kind__: "active";
        active: boolean;
    } | {
        __kind__: "notFound";
        notFound: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPairingStatus(arg0);
                return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPairingStatus(arg0);
            return from_candid_variant_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRewardPoints(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardPoints(arg0);
            return result;
        }
    }
    async issueGiftCard(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.issueGiftCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.issueGiftCard(arg0, arg1);
            return result;
        }
    }
    async lookupWPayOrder(arg0: string): Promise<CustomerOrder | null> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupWPayOrder(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupWPayOrder(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async markOrderPaidByCode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markOrderPaidByCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markOrderPaidByCode(arg0);
            return result;
        }
    }
    async markPairingCodeUsed(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPairingCodeUsed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPairingCodeUsed(arg0);
            return result;
        }
    }
    async markPairingPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markPairingPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markPairingPaid(arg0);
            return result;
        }
    }
    async markWPayOrderPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markWPayOrderPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markWPayOrderPaid(arg0);
            return result;
        }
    }
    async payWithCustomerCard(arg0: string, arg1: number, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: CustomerCard;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.payWithCustomerCard(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.payWithCustomerCard(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async placeCustomerOrder(arg0: string, arg1: Array<MenuItem>, arg2: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeCustomerOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeCustomerOrder(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async processCardDevicePayment(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.processCardDevicePayment(arg0, arg1, arg2, arg3, arg4);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processCardDevicePayment(arg0, arg1, arg2, arg3, arg4);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemForGiftCard(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemForGiftCard(arg0, arg1);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemForGiftCard(arg0, arg1);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async redeemRewardPoints(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemRewardPoints(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemRewardPoints(arg0);
            return result;
        }
    }
    async removeMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMenuItem(arg0);
            return result;
        }
    }
    async setPairingOrder(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPairingOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPairingOrder(arg0, arg1);
            return result;
        }
    }
    async signIn(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.signIn(arg0, arg1);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signIn(arg0, arg1);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async signUp(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.signUp(arg0, arg1);
                return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUp(arg0, arg1);
            return from_candid_variant_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, arg1, to_candid_opt_n2(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updatePairingCart(arg0: string, arg1: Array<MenuItem>, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePairingCart(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePairingCart(arg0, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async useGiftCard(arg0: string, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.useGiftCard(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.useGiftCard(arg0, arg1);
            return result;
        }
    }
    async validateCustomCreditCard(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCustomCreditCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCustomCreditCard(arg0);
            return result;
        }
    }
    async validatePairingCode(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validatePairingCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validatePairingCode(arg0);
            return result;
        }
    }
}
function from_candid_CustomerOrder_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerOrder): CustomerOrder {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomerOrder]): CustomerOrder | null {
    return value.length === 0 ? null : from_candid_CustomerOrder_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        status: string;
        total: number;
        orderId: [] | [bigint];
        items: Array<_MenuItem>;
    }]): {
    status: string;
    total: number;
    orderId?: bigint;
    items: Array<MenuItem>;
} | null {
    return value.length === 0 ? null : from_candid_record_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: string;
    total: number;
    paymentMethod: [] | [string];
    wPayCode: [] | [string];
    timestamp: _Time;
    items: Array<_MenuItem>;
}): {
    id: bigint;
    customerName: string;
    status: string;
    total: number;
    paymentMethod?: string;
    wPayCode?: string;
    timestamp: Time;
    items: Array<MenuItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: value.status,
        total: value.total,
        paymentMethod: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.paymentMethod)),
        wPayCode: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.wPayCode)),
        timestamp: value.timestamp,
        items: from_candid_vec_n12(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    category: [] | [string];
    price: number;
}): {
    name: string;
    category?: string;
    price: number;
} {
    return {
        name: value.name,
        category: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.category)),
        price: value.price
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cards: Array<_CustomerCard>;
    orders: Array<_CustomerOrder>;
    points: bigint;
}): {
    cards: Array<CustomerCard>;
    orders: Array<CustomerOrder>;
    points: bigint;
} {
    return {
        cards: value.cards,
        orders: from_candid_vec_n8(_uploadFile, _downloadFile, value.orders),
        points: value.points
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    total: number;
    orderId: [] | [bigint];
    items: Array<_MenuItem>;
}): {
    status: string;
    total: number;
    orderId?: bigint;
    items: Array<MenuItem>;
} {
    return {
        status: value.status,
        total: value.total,
        orderId: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.orderId)),
        items: from_candid_vec_n12(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _CustomerCard;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: CustomerCard;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        cards: Array<_CustomerCard>;
        orders: Array<_CustomerOrder>;
        points: bigint;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        cards: Array<CustomerCard>;
        orders: Array<CustomerOrder>;
        points: bigint;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n16(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: boolean;
} | {
    notFound: null;
}): {
    __kind__: "active";
    active: boolean;
} | {
    __kind__: "notFound";
    notFound: null;
} {
    return "active" in value ? {
        __kind__: "active",
        active: value.active
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_CustomerCard>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<CustomerCard>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerOrder>): Array<CustomerOrder> {
    return value.map((x)=>from_candid_CustomerOrder_n9(_uploadFile, _downloadFile, x));
}
function to_candid_MenuItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuItem): _MenuItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    category?: string;
    price: number;
}): {
    name: string;
    category: [] | [string];
    price: number;
} {
    return {
        name: value.name,
        category: value.category ? candid_some(value.category) : candid_none(),
        price: value.price
    };
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MenuItem>): Array<_MenuItem> {
    return value.map((x)=>to_candid_MenuItem_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
